FROM balenalib/%%BALENA_MACHINE_NAME%%-debian

# Install dependencies
RUN apt-get update && \
  apt-get install -yq \
    python3 \
    python3-dev \
    python3-pip \
    python3-setuptools

# pip install python deps from requirements.txt
# For caching until requirements.txt changes
COPY ./requirements.txt /requirements.txt
RUN pip3 install -r /requirements.txt

COPY . /usr/src/app
WORKDIR /usr/src/app

CMD ["python3", "main.py"]
